<?php

return [
    'path' => base_path('modules'),
    'host_version' => env('EASYADMIN_CORE_VERSION', '8.0.0'),
    'asset_route_prefix' => 'module-assets',
    'allowed_types' => ['core', 'official', 'partner', 'community', 'private'],
    'local_unsigned_types' => ['core', 'official', 'private'],
    'production_requires_signature_for' => ['partner', 'community'],
    'production_in_process_trust_levels' => ['core', 'official', 'private'],
    'signing_key' => env('MODULE_SIGNING_KEY', ''),
    'registration_ticket_key' => env('MODULE_REGISTRATION_TICKET_KEY', ''),
    'legacy_client_routes' => [
        'qingyu_ip_agent' => [
            'enabled' => env('MODULE_LEGACY_CLIENT_ROUTES_ENABLED', true),
            'sunset' => env('MODULE_LEGACY_CLIENT_SUNSET', 'Sun, 31 Jan 2027 00:00:00 GMT'),
            'successors' => [
                'bootstrap' => '/api/v1/modules/qingyu-ip-agent/bootstrap',
                'register' => '/api/v1/auth/modules/qingyu_ip_agent/register',
                'login' => '/api/v1/auth/modules/qingyu_ip_agent/login',
                'profile' => '/api/v1/auth/profile',
                'activate' => '/api/v1/modules/qingyu-ip-agent/activation-codes/redeem',
                'parseContent' => '/api/v1/modules/qingyu-ip-agent/content/parse',
                'rewrite' => '/api/v1/modules/qingyu-ip-agent/content/rewrite',
                'sampleAudio' => '/api/v1/modules/qingyu-ip-agent/sample-audio',
                'sendResetCode' => '/api/v1/auth/password/forgot',
                'resetPassword' => '/api/v1/auth/password/reset',
                'logout' => '/api/v1/auth/logout',
                'updateProfile' => '/api/v1/auth/profile',
                'updatePassword' => '/api/v1/auth/password/reset',
            ],
        ],
    ],
    'reserved_admin_prefixes' => [],
    'allowed_permissions' => [
        'menu:write',
        'node:write',
        'api:user',
        'user:read',
        'invite:read',
        'vip:read',
        'vip:write',
        'activation-code:write',
        'balance:read',
        'balance:write',
        'affiliate:write',
        'audit:write',
        'notification:write',
    ],
    'cache_key' => 'easyadmin8.modules.enabled',
    'integrity_cache_seconds' => env('MODULE_INTEGRITY_CACHE_SECONDS', 60),
    'api_default_daily_quota' => 500,
    'api_request_lease_seconds' => max(30, (int) env('MODULE_API_REQUEST_LEASE_SECONDS', 180)),
    'api_daily_quotas' => [
        'qingyu_ip_agent' => [
            'activation.redeem' => 50,
            'content.parse' => 200,
            'content.rewrite' => 100,
        ],
    ],
];
